[project]
name = "stm32f303re-dongle"
version = "0.1.0"
description = "Complementary Python API for the STM32F303RE-Dongle-Firmware Project"
readme = "README.md"
authors = [
    { name = "Mark Angelo Tarvina", email = "mttarvina@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.2",
    "pyserial>=3.5",
    "signals-toolkit",
]

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"

[tool.uv.sources]
signals-toolkit = { path = "../../signals_toolkit/signals_toolkit", editable = true }
